services:
  openpose-ros2:
    build: .
    network_mode: host
    ipc: host
    tty: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /run/user/1000/at-spi:/run/user/1000/at-spi
      - ./fastrtps-profile.xml:/tmp/fastrtps-profile.xml
      - ./workspace:/root/workspace
      - openpose:/root/openpose
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - FASTRTPS_DEFAULT_PROFILES_FILE=/tmp/fastrtps-profile.xml
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities:
              - gpu
volumes:
  openpose:
